name: Build the app and creates artifacts

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew



      - name: Build jar
        run: ./gradlew desktop:jar

      - name: Build deb/rpm
        run: ./gradlew desktop:jpackage

      - name: Fix file names
        run: mv desktop/build/lib/*.jar GdxJpackage-linux.jar && mv desktop/build/jpackage/*.deb GdxJpackage.deb && mv desktop/build/jpackage/*.rpm GdxJpackage.rpm


      - name: Upload jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage-linux.jar
          path: GdxJpackage-linux.jar

      - name: Upload deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage.deb
          path: GdxJpackage.deb
      - name: Upload rmp artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage.rpm
          path: GdxJpackage.rpm




  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14



      - name: Build jar
        run: ./gradlew.bat desktop:jar

      - name: Build exe/msi
        run: ./gradlew.bat desktop:jpackage

      - name: Fix file names
        run: mv desktop/build/lib/*.jar GdxJpackage-windows.jar && mv desktop/build/jpackage/*.exe GdxJpackage.exe && mv desktop/build/jpackage/*.msi GdxJpackage.msi


      - name: Upload jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage-windows.jar
          path: GdxJpackage-windows.jar

      - name: Upload exe artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage.exe
          path: GdxJpackage.exe
      - name: Upload msi artifact
        uses: actions/upload-artifact@v2
        with:
          name: GdxJpackage.msi
          path: GdxJpackage.msi
